### ISSUE TITLE
Crash on Game Initialization

### ISSUE THREAD

**Issue by nobodyawesomer** [TelepathicGrunt/Bumblezone-Fabric#34]
Hi, I'm getting a crash when I start Minecraft with the bumblezone mod. I'm using MultiMC and have attached the crash log. The error is `Could not execute entrypoint stage 'client' due to errors, provided by 'the_bumblezone'!`.

[crash-2021-10-30_17.27.20-client.txt](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/7447819/crash-2021-10-30_17.27.20-client.txt)

Please let me know if there's any more information I can provide that will help. I have launched with many of these mods previously and the crash is only happening now I added several new mods. I will try to disable combinations of the mods that I just added and see which one of those may have been causing the compatibility problem.

Edit: I have tried disabling all the other mods except The Bumblezone and its dependencies, and the issue persists. Hope that helps :)

**Comment by TelepathicGrunt** [comment]
It seems a mixin of mine is broken even though I thought I tested this. Will look into it soon

**Comment by TelepathicGrunt** [comment]
v3.2.6 bumblezone is now out and should fix the crash. The issue is I had a mixin that goes into Fabric API. However, I had an old version of fabric API in my dev so when using a newer version of the api, my mixin crashed since the class I was targeting was moved to a different spot in the api. v3.2.6 now requires Fabric API 0.41.0 or newer.

Thank you for reporting this!
