### ISSUE TITLE
Data Fixer log spam

### ISSUE THREAD

**Issue by serioos** [TelepathicGrunt/Bumblezone-Fabric#36]
The server throws these errors when it starts up. 

[10:37:33] [main/ERROR]: No data fixer registered for honey_slime
[10:37:33] [main/ERROR]: No data fixer registered for beehemoth
[10:37:33] [main/ERROR]: No data fixer registered for pollen_puff

**Comment by TelepathicGrunt** [comment]
Yeah it’s just logspam. Data fixer is part of Data Fixer Upper which is used to allow Minecraft worlds to convert to newer version’s data formats. However, mods do not have a good way to register data fixers for entities and so, we can’t really tell it that it is intentional. I think there’s a Fabric API method I should use that skip that data fixer check but otherwise, there’s no issue or problem. Everything is working as intended.

**Comment by TelepathicGrunt** [comment]
v3.4.1 is out and should reduce the logspam
