### ISSUE TITLE
[Fabric 1.18.1] Incompatibility with Identity mod

### ISSUE THREAD

**Issue by James103** [TelepathicGrunt/Bumblezone-Fabric#68]
Somebody just posted the following crash report in https://github.com/Draylar/identity/issues/344:
https://mclo.gs/wurBl3f

The game appears to be crashing here because `entity.level` is null since the entities are added and rendered in a client-side GUI only.
https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/6bca5d128eada4790695ffd31428452625437d08/src/main/java/com/telepathicgrunt/the_bumblezone/entities/BeeAggression.java#L171-L172

The fix may be just to append ` entity.level != null &&` to the end of line 171, but I haven't tested to see if that fixes the crash.

**Comment by TelepathicGrunt** [comment]
I am no longer supporting minecraft versions older than latest. Though the real question here is why are they creating an entity without a level? That’s very concerning tbh. 

I’ll add the check to the 1.18.2 or 1.19 version depending when my next update comes out. Though they should really make entities have a level (world) always or else I feel like other mods would also crash as well since i would think most modders would not expect entities to have a null world

**Comment by TelepathicGrunt** [comment]
check is added in latest 1.18.2 version now
