### ISSUE TITLE
Worlds using Experimental Settings are not supported

### ISSUE THREAD

**Issue by decon-structed** [TelepathicGrunt/Bumblezone-Fabric#7]
When creating a new world, I get the following warning:

> #### Worlds using Experimental Settings are not supported
> This world uses experimental settings that could stop working at any time. We cannot guarantee it will load or work. Here be dragons!

I wasn't able to find any useful information about this message on Google. What does this mean, and is there anything I should watch out for?

**Comment by TelepathicGrunt** [comment]
It's just a vague warning mojang made that happens when you use any mod with dimensions or dimension datapacks as the dimension stuff is very work-in-progress on mojang's side. There's a fabric mod i think that disables that warning screen. 

If there's any issue you're facing with the mod, just let me know!

**Comment by TelepathicGrunt** [comment]
https://www.curseforge.com/minecraft/mc-mods/experimentaway

Here's the mod that disables that warning screen

**Comment by decon-structed** [comment]
Thanks
