### ISSUE TITLE
crashes server when a specific player loads an entity, but shows bumblezone in crash logs

### ISSUE THREAD

**Issue by ericvasile** [TelepathicGrunt/Bumblezone-Fabric#77]
I was wondering if you could assist me in reading and understanding this. It seems that for some reason, one specific player from our group of three has issues when loading certain entities. However, this only occurs randomly, which leads me believe to be entity corruption issues, but the crash logs show bumble zone as being the cause. 

Crash Logs: https://mclo.gs/28TI7ro

**Comment by TelepathicGrunt** [comment]
This crash was already fixed in v6.1.4 Bumblezone. Please update bumblezone to latest version and the issue should go away. Specifically, this was the change introduced in v6.1.4:

##### Mod Compat:
Fixed crash if a mod passes null into beehivetileentity.emptyAllLivingFromHive.
 I added a null check to my code to prevent a crash.
 
 if you still get the issue with latest bumblezone, let me know with new log and I'll re-open this.

**Comment by ericvasile** [comment]
So: is this causing the "exception ticking world". Because this only occurs to one person on the server, and not to the other two members. It leads me to believe that it's a client side issue. 

I can't update it since I'm using the BetterMC v4 pack and using it through exaroton, which allows installation of modpacks but can't edit the mods in the server files themselves. 

Let me know.
